[project]
name = "reports"
version = "0.1.0"
description = "AETHER Reports"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-git-committers-plugin-2>=2.5.0",
    "mkdocs-git-revision-date-localized-plugin>=1.4.5",
    "mkdocs-material>=9.6.11",
]
